POST http://localhost:3003/pokedex
Content-type: application/json

{
  "pokemon": "pikachuu"
}
###
GET http://localhost:3003/pokedex
Content-type: application/json

###
DELETE http://localhost:3003/pokedex
Content-type: application/json

{
  "pokemon": "pikachuu"
}